// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: poker.proto

package pokerproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          string                 `protobuf:"bytes,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Suit          string                 `protobuf:"bytes,2,opt,name=suit,proto3" json:"suit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *Card) GetSuit() string {
	if x != nil {
		return x.Suit
	}
	return ""
}

type Seat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stack           int64                  `protobuf:"varint,3,opt,name=stack,proto3" json:"stack,omitempty"`
	State           string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Contributed     int64                  `protobuf:"varint,5,opt,name=contributed,proto3" json:"contributed,omitempty"`
	HoleCards       []string               `protobuf:"bytes,6,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	Equity          *float64               `protobuf:"fixed64,7,opt,name=equity,proto3,oneof" json:"equity,omitempty"`
	HandCategory    string                 `protobuf:"bytes,8,opt,name=hand_category,json=handCategory,proto3" json:"hand_category,omitempty"`
	ConnectionState string                 `protobuf:"bytes,9,opt,name=connection_state,json=connectionState,proto3" json:"connection_state,omitempty"` // connected | disconnected
	// True when this seat belongs to the hand identified by TableSnapshot.hand_id.
	// A seat can be active while false when it returns mid-hand for the next deal.
	// Optional so a new client can distinguish an old server (field absent)
	// from an explicit false for a player waiting for the next hand.
	DealtIn *bool `protobuf:"varint,10,opt,name=dealt_in,json=dealtIn,proto3,oneof" json:"dealt_in,omitempty"`
	// The next-hand opt-in. During a live hand a player can be folded from the
	// current round while ready=false already communicates "paused afterwards".
	Ready *bool `protobuf:"varint,11,opt,name=ready,proto3,oneof" json:"ready,omitempty"`
	// Public reveal mask for the two hole-card positions. A player's own cards
	// are always visible to themselves; this mask says what everyone may see.
	HoleCardsRevealed []bool `protobuf:"varint,12,rep,packed,name=hole_cards_revealed,json=holeCardsRevealed,proto3" json:"hole_cards_revealed,omitempty"`
	// Stack before this hand posted blinds or accepted any wager. Optional so
	// clients can fall back safely while API instances are rolling.
	StackAtHandStart *int64 `protobuf:"varint,13,opt,name=stack_at_hand_start,json=stackAtHandStart,proto3,oneof" json:"stack_at_hand_start,omitempty"`
	// Durable decision reserve in milliseconds. Zero is a valid exhausted
	// balance, so clients must not replace it with a default.
	TimeBankMs int64 `protobuf:"varint,14,opt,name=time_bank_ms,json=timeBankMs,proto3" json:"time_bank_ms,omitempty"`
	// Canonical server-side evaluator score. Higher wins; equal is a split.
	// Only present when the same visibility rules allow hand_category.
	HandScore      uint32  `protobuf:"varint,15,opt,name=hand_score,json=handScore,proto3" json:"hand_score,omitempty"`
	AvatarUrl      *string `protobuf:"bytes,16,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	PlaystyleBadge *string `protobuf:"bytes,17,opt,name=playstyle_badge,json=playstyleBadge,proto3,oneof" json:"playstyle_badge,omitempty"`
	RunItTwice     *bool   `protobuf:"varint,18,opt,name=run_it_twice,json=runItTwice,proto3,oneof" json:"run_it_twice,omitempty"`
	AutoRebuy      *bool   `protobuf:"varint,19,opt,name=auto_rebuy,json=autoRebuy,proto3,oneof" json:"auto_rebuy,omitempty"`
	// Running per-table win/loss streak: positive counts consecutive hand
	// wins, negative counts consecutive losses, zero means no streak (no
	// badge). Public, like the D/SB/BB role badge — every viewer sees it.
	CurrentStreak int32 `protobuf:"varint,20,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{1}
}

func (x *Seat) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Seat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seat) GetStack() int64 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Seat) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Seat) GetContributed() int64 {
	if x != nil {
		return x.Contributed
	}
	return 0
}

func (x *Seat) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *Seat) GetEquity() float64 {
	if x != nil && x.Equity != nil {
		return *x.Equity
	}
	return 0
}

func (x *Seat) GetHandCategory() string {
	if x != nil {
		return x.HandCategory
	}
	return ""
}

func (x *Seat) GetConnectionState() string {
	if x != nil {
		return x.ConnectionState
	}
	return ""
}

func (x *Seat) GetDealtIn() bool {
	if x != nil && x.DealtIn != nil {
		return *x.DealtIn
	}
	return false
}

func (x *Seat) GetReady() bool {
	if x != nil && x.Ready != nil {
		return *x.Ready
	}
	return false
}

func (x *Seat) GetHoleCardsRevealed() []bool {
	if x != nil {
		return x.HoleCardsRevealed
	}
	return nil
}

func (x *Seat) GetStackAtHandStart() int64 {
	if x != nil && x.StackAtHandStart != nil {
		return *x.StackAtHandStart
	}
	return 0
}

func (x *Seat) GetTimeBankMs() int64 {
	if x != nil {
		return x.TimeBankMs
	}
	return 0
}

func (x *Seat) GetHandScore() uint32 {
	if x != nil {
		return x.HandScore
	}
	return 0
}

func (x *Seat) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *Seat) GetPlaystyleBadge() string {
	if x != nil && x.PlaystyleBadge != nil {
		return *x.PlaystyleBadge
	}
	return ""
}

func (x *Seat) GetRunItTwice() bool {
	if x != nil && x.RunItTwice != nil {
		return *x.RunItTwice
	}
	return false
}

func (x *Seat) GetAutoRebuy() bool {
	if x != nil && x.AutoRebuy != nil {
		return *x.AutoRebuy
	}
	return false
}

func (x *Seat) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

type BlindEscalation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalMinutes int32                  `protobuf:"varint,1,opt,name=interval_minutes,json=intervalMinutes,proto3" json:"interval_minutes,omitempty"`
	Multiplier      int32                  `protobuf:"varint,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Max             int64                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlindEscalation) Reset() {
	*x = BlindEscalation{}
	mi := &file_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindEscalation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindEscalation) ProtoMessage() {}

func (x *BlindEscalation) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindEscalation.ProtoReflect.Descriptor instead.
func (*BlindEscalation) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{2}
}

func (x *BlindEscalation) GetIntervalMinutes() int32 {
	if x != nil {
		return x.IntervalMinutes
	}
	return 0
}

func (x *BlindEscalation) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *BlindEscalation) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Room struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RoomId               string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Visibility           string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CurrencyMode         string                 `protobuf:"bytes,3,opt,name=currency_mode,json=currencyMode,proto3" json:"currency_mode,omitempty"`
	SmallBlind           int64                  `protobuf:"varint,4,opt,name=small_blind,json=smallBlind,proto3" json:"small_blind,omitempty"`
	BigBlind             int64                  `protobuf:"varint,5,opt,name=big_blind,json=bigBlind,proto3" json:"big_blind,omitempty"`
	MaxSeats             int32                  `protobuf:"varint,6,opt,name=max_seats,json=maxSeats,proto3" json:"max_seats,omitempty"`
	BuyInMin             int64                  `protobuf:"varint,7,opt,name=buy_in_min,json=buyInMin,proto3" json:"buy_in_min,omitempty"`
	BuyInMax             int64                  `protobuf:"varint,8,opt,name=buy_in_max,json=buyInMax,proto3" json:"buy_in_max,omitempty"`
	EntryFeeCents        int64                  `protobuf:"varint,9,opt,name=entry_fee_cents,json=entryFeeCents,proto3" json:"entry_fee_cents,omitempty"`
	ShareCode            string                 `protobuf:"bytes,10,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`
	BlindEscalation      *BlindEscalation       `protobuf:"bytes,11,opt,name=blind_escalation,json=blindEscalation,proto3" json:"blind_escalation,omitempty"`
	TurnTimeoutSeconds   int32                  `protobuf:"varint,12,opt,name=turn_timeout_seconds,json=turnTimeoutSeconds,proto3" json:"turn_timeout_seconds,omitempty"`
	EquityDisplayEnabled bool                   `protobuf:"varint,13,opt,name=equity_display_enabled,json=equityDisplayEnabled,proto3" json:"equity_display_enabled,omitempty"`
	Status               string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	SeatsTaken           int32                  `protobuf:"varint,15,opt,name=seats_taken,json=seatsTaken,proto3" json:"seats_taken,omitempty"`
	CreatedBy            string                 `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RunItTwiceEnabled    bool                   `protobuf:"varint,18,opt,name=run_it_twice_enabled,json=runItTwiceEnabled,proto3" json:"run_it_twice_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{3}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Room) GetCurrencyMode() string {
	if x != nil {
		return x.CurrencyMode
	}
	return ""
}

func (x *Room) GetSmallBlind() int64 {
	if x != nil {
		return x.SmallBlind
	}
	return 0
}

func (x *Room) GetBigBlind() int64 {
	if x != nil {
		return x.BigBlind
	}
	return 0
}

func (x *Room) GetMaxSeats() int32 {
	if x != nil {
		return x.MaxSeats
	}
	return 0
}

func (x *Room) GetBuyInMin() int64 {
	if x != nil {
		return x.BuyInMin
	}
	return 0
}

func (x *Room) GetBuyInMax() int64 {
	if x != nil {
		return x.BuyInMax
	}
	return 0
}

func (x *Room) GetEntryFeeCents() int64 {
	if x != nil {
		return x.EntryFeeCents
	}
	return 0
}

func (x *Room) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

func (x *Room) GetBlindEscalation() *BlindEscalation {
	if x != nil {
		return x.BlindEscalation
	}
	return nil
}

func (x *Room) GetTurnTimeoutSeconds() int32 {
	if x != nil {
		return x.TurnTimeoutSeconds
	}
	return 0
}

func (x *Room) GetEquityDisplayEnabled() bool {
	if x != nil {
		return x.EquityDisplayEnabled
	}
	return false
}

func (x *Room) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Room) GetSeatsTaken() int32 {
	if x != nil {
		return x.SeatsTaken
	}
	return 0
}

func (x *Room) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Room) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Room) GetRunItTwiceEnabled() bool {
	if x != nil {
		return x.RunItTwiceEnabled
	}
	return false
}

type LegalActions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Actions             []string               `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`                                                     // subset of fold|check|call|raise
	CallAmount          int64                  `protobuf:"varint,2,opt,name=call_amount,json=callAmount,proto3" json:"call_amount,omitempty"`                            // chips owed to call (0 when a check is available)
	MinRaiseTo          int64                  `protobuf:"varint,3,opt,name=min_raise_to,json=minRaiseTo,proto3" json:"min_raise_to,omitempty"`                          // smallest total bet a raise may reach
	MaxRaiseTo          int64                  `protobuf:"varint,4,opt,name=max_raise_to,json=maxRaiseTo,proto3" json:"max_raise_to,omitempty"`                          // largest total bet (all-in): viewer stack + already contributed
	Step                int64                  `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`                                                          // raise increment for the + / - stepper
	CurrentContribution int64                  `protobuf:"varint,6,opt,name=current_contribution,json=currentContribution,proto3" json:"current_contribution,omitempty"` // viewer contribution in this betting street
	CurrentBet          int64                  `protobuf:"varint,7,opt,name=current_bet,json=currentBet,proto3" json:"current_bet,omitempty"`                            // highest contribution in this betting street
	OneThirdPotRaiseTo  int64                  `protobuf:"varint,8,opt,name=one_third_pot_raise_to,json=oneThirdPotRaiseTo,proto3" json:"one_third_pot_raise_to,omitempty"`
	HalfPotRaiseTo      int64                  `protobuf:"varint,9,opt,name=half_pot_raise_to,json=halfPotRaiseTo,proto3" json:"half_pot_raise_to,omitempty"`
	TwoThirdsPotRaiseTo int64                  `protobuf:"varint,10,opt,name=two_thirds_pot_raise_to,json=twoThirdsPotRaiseTo,proto3" json:"two_thirds_pot_raise_to,omitempty"`
	PotRaiseTo          int64                  `protobuf:"varint,11,opt,name=pot_raise_to,json=potRaiseTo,proto3" json:"pot_raise_to,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LegalActions) Reset() {
	*x = LegalActions{}
	mi := &file_poker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegalActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegalActions) ProtoMessage() {}

func (x *LegalActions) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegalActions.ProtoReflect.Descriptor instead.
func (*LegalActions) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{4}
}

func (x *LegalActions) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *LegalActions) GetCallAmount() int64 {
	if x != nil {
		return x.CallAmount
	}
	return 0
}

func (x *LegalActions) GetMinRaiseTo() int64 {
	if x != nil {
		return x.MinRaiseTo
	}
	return 0
}

func (x *LegalActions) GetMaxRaiseTo() int64 {
	if x != nil {
		return x.MaxRaiseTo
	}
	return 0
}

func (x *LegalActions) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *LegalActions) GetCurrentContribution() int64 {
	if x != nil {
		return x.CurrentContribution
	}
	return 0
}

func (x *LegalActions) GetCurrentBet() int64 {
	if x != nil {
		return x.CurrentBet
	}
	return 0
}

func (x *LegalActions) GetOneThirdPotRaiseTo() int64 {
	if x != nil {
		return x.OneThirdPotRaiseTo
	}
	return 0
}

func (x *LegalActions) GetHalfPotRaiseTo() int64 {
	if x != nil {
		return x.HalfPotRaiseTo
	}
	return 0
}

func (x *LegalActions) GetTwoThirdsPotRaiseTo() int64 {
	if x != nil {
		return x.TwoThirdsPotRaiseTo
	}
	return 0
}

func (x *LegalActions) GetPotRaiseTo() int64 {
	if x != nil {
		return x.PotRaiseTo
	}
	return 0
}

type Pot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Amount            int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	EligiblePlayerIds []string               `protobuf:"bytes,2,rep,name=eligible_player_ids,json=eligiblePlayerIds,proto3" json:"eligible_player_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Pot) Reset() {
	*x = Pot{}
	mi := &file_poker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pot) ProtoMessage() {}

func (x *Pot) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pot.ProtoReflect.Descriptor instead.
func (*Pot) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{5}
}

func (x *Pot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pot) GetEligiblePlayerIds() []string {
	if x != nil {
		return x.EligiblePlayerIds
	}
	return nil
}

type PotResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Amount            int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`                                 // gross layer amount before rake
	PayoutAmount      int64                  `protobuf:"varint,2,opt,name=payout_amount,json=payoutAmount,proto3" json:"payout_amount,omitempty"` // net contested payout, or refund amount
	EligiblePlayerIds []string               `protobuf:"bytes,3,rep,name=eligible_player_ids,json=eligiblePlayerIds,proto3" json:"eligible_player_ids,omitempty"`
	WinnerPlayerIds   []string               `protobuf:"bytes,4,rep,name=winner_player_ids,json=winnerPlayerIds,proto3" json:"winner_player_ids,omitempty"`                                   // empty for refunds
	Payouts           map[string]int64       `protobuf:"bytes,5,rep,name=payouts,proto3" json:"payouts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // exact per-player credits, including odd chips
	Refund            bool                   `protobuf:"varint,6,opt,name=refund,proto3" json:"refund,omitempty"`                                                                             // true for uncalled/orphaned contribution returns
	Runout            int32                  `protobuf:"varint,7,opt,name=runout,proto3" json:"runout,omitempty"`                                                                             // 1 or 2 for RIT; 0 for a normal hand/refund
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PotResult) Reset() {
	*x = PotResult{}
	mi := &file_poker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PotResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PotResult) ProtoMessage() {}

func (x *PotResult) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PotResult.ProtoReflect.Descriptor instead.
func (*PotResult) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{6}
}

func (x *PotResult) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PotResult) GetPayoutAmount() int64 {
	if x != nil {
		return x.PayoutAmount
	}
	return 0
}

func (x *PotResult) GetEligiblePlayerIds() []string {
	if x != nil {
		return x.EligiblePlayerIds
	}
	return nil
}

func (x *PotResult) GetWinnerPlayerIds() []string {
	if x != nil {
		return x.WinnerPlayerIds
	}
	return nil
}

func (x *PotResult) GetPayouts() map[string]int64 {
	if x != nil {
		return x.Payouts
	}
	return nil
}

func (x *PotResult) GetRefund() bool {
	if x != nil {
		return x.Refund
	}
	return false
}

func (x *PotResult) GetRunout() int32 {
	if x != nil {
		return x.Runout
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_poker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TableReaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ReactionId     string                 `protobuf:"bytes,3,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,4,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TableReaction) Reset() {
	*x = TableReaction{}
	mi := &file_poker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableReaction) ProtoMessage() {}

func (x *TableReaction) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableReaction.ProtoReflect.Descriptor instead.
func (*TableReaction) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{8}
}

func (x *TableReaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TableReaction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *TableReaction) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *TableReaction) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *TableReaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TableReaction) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type TableSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Stage                string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Board                []string               `protobuf:"bytes,2,rep,name=board,proto3" json:"board,omitempty"`
	Seats                []*Seat                `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	Payouts              map[string]int64       `protobuf:"bytes,4,rep,name=payouts,proto3" json:"payouts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Winners              []string               `protobuf:"bytes,5,rep,name=winners,proto3" json:"winners,omitempty"`
	Rake                 int64                  `protobuf:"varint,6,opt,name=rake,proto3" json:"rake,omitempty"`
	CurrentPlayerId      string                 `protobuf:"bytes,7,opt,name=current_player_id,json=currentPlayerId,proto3" json:"current_player_id,omitempty"`
	LegalActions         *LegalActions          `protobuf:"bytes,8,opt,name=legal_actions,json=legalActions,proto3" json:"legal_actions,omitempty"`
	ActionDeadlineUnixMs int64                  `protobuf:"varint,9,opt,name=action_deadline_unix_ms,json=actionDeadlineUnixMs,proto3" json:"action_deadline_unix_ms,omitempty"`
	NextHandUnixMs       int64                  `protobuf:"varint,10,opt,name=next_hand_unix_ms,json=nextHandUnixMs,proto3" json:"next_hand_unix_ms,omitempty"`
	WonWithoutShowdown   bool                   `protobuf:"varint,11,opt,name=won_without_showdown,json=wonWithoutShowdown,proto3" json:"won_without_showdown,omitempty"`
	ShuffleCommitHash    string                 `protobuf:"bytes,12,opt,name=shuffle_commit_hash,json=shuffleCommitHash,proto3" json:"shuffle_commit_hash,omitempty"`
	ShuffleServerSeedHex string                 `protobuf:"bytes,13,opt,name=shuffle_server_seed_hex,json=shuffleServerSeedHex,proto3" json:"shuffle_server_seed_hex,omitempty"`
	SmallBlindPlayerId   string                 `protobuf:"bytes,14,opt,name=small_blind_player_id,json=smallBlindPlayerId,proto3" json:"small_blind_player_id,omitempty"`
	BigBlindPlayerId     string                 `protobuf:"bytes,15,opt,name=big_blind_player_id,json=bigBlindPlayerId,proto3" json:"big_blind_player_id,omitempty"`
	DealerPlayerId       string                 `protobuf:"bytes,16,opt,name=dealer_player_id,json=dealerPlayerId,proto3" json:"dealer_player_id,omitempty"`
	SnapshotVersion      uint64                 `protobuf:"varint,17,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Pots                 []*Pot                 `protobuf:"bytes,18,rep,name=pots,proto3" json:"pots,omitempty"`
	HandId               string                 `protobuf:"bytes,19,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	PotResults           []*PotResult           `protobuf:"bytes,20,rep,name=pot_results,json=potResults,proto3" json:"pot_results,omitempty"`
	// Allows clients to apply explicit compatibility fallbacks during rolling
	// deployments instead of mistaking absent proto3 fields for false.
	ProtocolVersion   uint32 `protobuf:"varint,21,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	IdleRemovalUnixMs int64  `protobuf:"varint,22,opt,name=idle_removal_unix_ms,json=idleRemovalUnixMs,proto3" json:"idle_removal_unix_ms,omitempty"`
	// End of the normal room clock. The interval between this and
	// action_deadline_unix_ms belongs to the current player's time bank.
	ActionBaseDeadlineUnixMs int64            `protobuf:"varint,23,opt,name=action_base_deadline_unix_ms,json=actionBaseDeadlineUnixMs,proto3" json:"action_base_deadline_unix_ms,omitempty"`
	ChatMessages             []*ChatMessage   `protobuf:"bytes,24,rep,name=chat_messages,json=chatMessages,proto3" json:"chat_messages,omitempty"`
	Reactions                []*TableReaction `protobuf:"bytes,25,rep,name=reactions,proto3" json:"reactions,omitempty"`
	// Viewer-scoped one-shot value: check_fold | fold | call | call_any | empty.
	ActionPreselection string `protobuf:"bytes,26,opt,name=action_preselection,json=actionPreselection,proto3" json:"action_preselection,omitempty"`
	// Frozen amount for a fixed "call" preselection; zero for every other mode.
	ActionPreselectionAmount int64 `protobuf:"varint,27,opt,name=action_preselection_amount,json=actionPreselectionAmount,proto3" json:"action_preselection_amount,omitempty"`
	// What this viewer would owe if action reached them now, even before their
	// turn. Viewer-scoped so the UI can offer an exact fixed-call preselection.
	ProspectiveCallAmount int64                   `protobuf:"varint,28,opt,name=prospective_call_amount,json=prospectiveCallAmount,proto3" json:"prospective_call_amount,omitempty"`
	RootCommitHash        string                  `protobuf:"bytes,29,opt,name=root_commit_hash,json=rootCommitHash,proto3" json:"root_commit_hash,omitempty"`
	RevealedCardSalts     map[int32]*RevealedSalt `protobuf:"bytes,30,rep,name=revealed_card_salts,json=revealedCardSalts,proto3" json:"revealed_card_salts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UnrevealedCardHashes  map[int32]string        `protobuf:"bytes,31,rep,name=unrevealed_card_hashes,json=unrevealedCardHashes,proto3" json:"unrevealed_card_hashes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RunoutCards           []string                `protobuf:"bytes,32,rep,name=runout_cards,json=runoutCards,proto3" json:"runout_cards,omitempty"`
	BoardTwo              []string                `protobuf:"bytes,33,rep,name=board_two,json=boardTwo,proto3" json:"board_two,omitempty"`
	BoardSplitAt          int32                   `protobuf:"varint,34,opt,name=board_split_at,json=boardSplitAt,proto3" json:"board_split_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TableSnapshot) Reset() {
	*x = TableSnapshot{}
	mi := &file_poker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSnapshot) ProtoMessage() {}

func (x *TableSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSnapshot.ProtoReflect.Descriptor instead.
func (*TableSnapshot) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{9}
}

func (x *TableSnapshot) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TableSnapshot) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *TableSnapshot) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *TableSnapshot) GetPayouts() map[string]int64 {
	if x != nil {
		return x.Payouts
	}
	return nil
}

func (x *TableSnapshot) GetWinners() []string {
	if x != nil {
		return x.Winners
	}
	return nil
}

func (x *TableSnapshot) GetRake() int64 {
	if x != nil {
		return x.Rake
	}
	return 0
}

func (x *TableSnapshot) GetCurrentPlayerId() string {
	if x != nil {
		return x.CurrentPlayerId
	}
	return ""
}

func (x *TableSnapshot) GetLegalActions() *LegalActions {
	if x != nil {
		return x.LegalActions
	}
	return nil
}

func (x *TableSnapshot) GetActionDeadlineUnixMs() int64 {
	if x != nil {
		return x.ActionDeadlineUnixMs
	}
	return 0
}

func (x *TableSnapshot) GetNextHandUnixMs() int64 {
	if x != nil {
		return x.NextHandUnixMs
	}
	return 0
}

func (x *TableSnapshot) GetWonWithoutShowdown() bool {
	if x != nil {
		return x.WonWithoutShowdown
	}
	return false
}

func (x *TableSnapshot) GetShuffleCommitHash() string {
	if x != nil {
		return x.ShuffleCommitHash
	}
	return ""
}

func (x *TableSnapshot) GetShuffleServerSeedHex() string {
	if x != nil {
		return x.ShuffleServerSeedHex
	}
	return ""
}

func (x *TableSnapshot) GetSmallBlindPlayerId() string {
	if x != nil {
		return x.SmallBlindPlayerId
	}
	return ""
}

func (x *TableSnapshot) GetBigBlindPlayerId() string {
	if x != nil {
		return x.BigBlindPlayerId
	}
	return ""
}

func (x *TableSnapshot) GetDealerPlayerId() string {
	if x != nil {
		return x.DealerPlayerId
	}
	return ""
}

func (x *TableSnapshot) GetSnapshotVersion() uint64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *TableSnapshot) GetPots() []*Pot {
	if x != nil {
		return x.Pots
	}
	return nil
}

func (x *TableSnapshot) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *TableSnapshot) GetPotResults() []*PotResult {
	if x != nil {
		return x.PotResults
	}
	return nil
}

func (x *TableSnapshot) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *TableSnapshot) GetIdleRemovalUnixMs() int64 {
	if x != nil {
		return x.IdleRemovalUnixMs
	}
	return 0
}

func (x *TableSnapshot) GetActionBaseDeadlineUnixMs() int64 {
	if x != nil {
		return x.ActionBaseDeadlineUnixMs
	}
	return 0
}

func (x *TableSnapshot) GetChatMessages() []*ChatMessage {
	if x != nil {
		return x.ChatMessages
	}
	return nil
}

func (x *TableSnapshot) GetReactions() []*TableReaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *TableSnapshot) GetActionPreselection() string {
	if x != nil {
		return x.ActionPreselection
	}
	return ""
}

func (x *TableSnapshot) GetActionPreselectionAmount() int64 {
	if x != nil {
		return x.ActionPreselectionAmount
	}
	return 0
}

func (x *TableSnapshot) GetProspectiveCallAmount() int64 {
	if x != nil {
		return x.ProspectiveCallAmount
	}
	return 0
}

func (x *TableSnapshot) GetRootCommitHash() string {
	if x != nil {
		return x.RootCommitHash
	}
	return ""
}

func (x *TableSnapshot) GetRevealedCardSalts() map[int32]*RevealedSalt {
	if x != nil {
		return x.RevealedCardSalts
	}
	return nil
}

func (x *TableSnapshot) GetUnrevealedCardHashes() map[int32]string {
	if x != nil {
		return x.UnrevealedCardHashes
	}
	return nil
}

func (x *TableSnapshot) GetRunoutCards() []string {
	if x != nil {
		return x.RunoutCards
	}
	return nil
}

func (x *TableSnapshot) GetBoardTwo() []string {
	if x != nil {
		return x.BoardTwo
	}
	return nil
}

func (x *TableSnapshot) GetBoardSplitAt() int32 {
	if x != nil {
		return x.BoardSplitAt
	}
	return 0
}

type RevealedSalt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          string                 `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	SaltHex       string                 `protobuf:"bytes,2,opt,name=salt_hex,json=saltHex,proto3" json:"salt_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealedSalt) Reset() {
	*x = RevealedSalt{}
	mi := &file_poker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealedSalt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealedSalt) ProtoMessage() {}

func (x *RevealedSalt) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealedSalt.ProtoReflect.Descriptor instead.
func (*RevealedSalt) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{10}
}

func (x *RevealedSalt) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *RevealedSalt) GetSaltHex() string {
	if x != nil {
		return x.SaltHex
	}
	return ""
}

// ClientMessage is sent from the client to the server.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "auth" | "ping" | "sync_state" | "ready" | "act" | "preselect_action" | "post_big_blind" | "show_cards" | "keep_seat" | "chat" | "reaction" | "bot_challenge" | "set_run_it_twice" | "peek_cards"
	// payload fields
	Token                   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                                                       // for auth frame
	ShareCode               string `protobuf:"bytes,3,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`                                              // for auth frame
	Ready                   bool   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`                                                                      // for ready command
	Action                  string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                                                                     // poker action, or check_fold|fold|call|call_any|empty for preselect_action
	Amount                  int64  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`                                                                    // bet amount for act; frozen call amount for preselect_action
	ActionId                string `protobuf:"bytes,7,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`                                                 // for act command
	Message                 string `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`                                                                   // for chat command
	ExpectedSnapshotVersion uint64 `protobuf:"varint,9,opt,name=expected_snapshot_version,json=expectedSnapshotVersion,proto3" json:"expected_snapshot_version,omitempty"` // optimistic precondition for act
	ExpectedHandId          string `protobuf:"bytes,10,opt,name=expected_hand_id,json=expectedHandId,proto3" json:"expected_hand_id,omitempty"`                            // prevents a delayed action crossing hands
	CardIndex               *int32 `protobuf:"varint,11,opt,name=card_index,json=cardIndex,proto3,oneof" json:"card_index,omitempty"`                                      // 0 or 1 for show_cards; absent means both (legacy)
	ReactionId              string `protobuf:"bytes,12,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`                                          // catalog key; never arbitrary display text
	TargetPlayerId          string `protobuf:"bytes,13,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`                            // required only by thrown-object reactions
	TurnstileToken          string `protobuf:"bytes,14,opt,name=turnstile_token,json=turnstileToken,proto3" json:"turnstile_token,omitempty"`                              // response token for an adaptive bot challenge
	RunItTwice              *bool  `protobuf:"varint,15,opt,name=run_it_twice,json=runItTwice,proto3,oneof" json:"run_it_twice,omitempty"`
	// Preselections are scoped to one betting street. Unlike a real action they
	// do not require an exact snapshot version: chat, reactions and unrelated
	// player actions may advance it without invalidating the viewer's intent.
	ExpectedStage string `protobuf:"bytes,16,opt,name=expected_stage,json=expectedStage,proto3" json:"expected_stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_poker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{11}
}

func (x *ClientMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientMessage) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

func (x *ClientMessage) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ClientMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ClientMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ClientMessage) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ClientMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientMessage) GetExpectedSnapshotVersion() uint64 {
	if x != nil {
		return x.ExpectedSnapshotVersion
	}
	return 0
}

func (x *ClientMessage) GetExpectedHandId() string {
	if x != nil {
		return x.ExpectedHandId
	}
	return ""
}

func (x *ClientMessage) GetCardIndex() int32 {
	if x != nil && x.CardIndex != nil {
		return *x.CardIndex
	}
	return 0
}

func (x *ClientMessage) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *ClientMessage) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *ClientMessage) GetTurnstileToken() string {
	if x != nil {
		return x.TurnstileToken
	}
	return ""
}

func (x *ClientMessage) GetRunItTwice() bool {
	if x != nil && x.RunItTwice != nil {
		return *x.RunItTwice
	}
	return false
}

func (x *ClientMessage) GetExpectedStage() string {
	if x != nil {
		return x.ExpectedStage
	}
	return ""
}

// ServerMessage is sent from the server to the client.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "connected" | "pong" | "state" | "chat" | "error" | "removed" | "achievement_unlocked" | "room_created" | "room_updated" | "payment_received" | "system_broadcast" | "sandbox_purchase_update" | "reaction_purchase_update"
	// payload fields
	ConnId   string         `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`       // for connected frame
	Snapshot *TableSnapshot `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                 // for state frame
	PlayerId string         `protobuf:"bytes,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // for chat frame, and destination for purchase update frames
	Message  string         `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                   // for chat frame, error message, or removed reason
	Code     string         `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`                         // for error/removed frames, or purchase update status (confirmed|refunded|expired|failed)
	Key      string         `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`                           // for achievement unlocked frame
	Stars    int32          `protobuf:"varint,8,opt,name=stars,proto3" json:"stars,omitempty"`                      // for achievement unlocked frame
	// lobby payload fields
	Room            *Room    `protobuf:"bytes,9,opt,name=room,proto3" json:"room,omitempty"`                                                // for room_created
	RoomId          string   `protobuf:"bytes,10,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                             // for room_updated
	SeatsTaken      int32    `protobuf:"varint,11,opt,name=seats_taken,json=seatsTaken,proto3" json:"seats_taken,omitempty"`                // for room_updated
	Amount          int64    `protobuf:"varint,12,opt,name=amount,proto3" json:"amount,omitempty"`                                          // for payment_received, or credits_granted for sandbox_purchase_update
	Text            string   `protobuf:"bytes,13,opt,name=text,proto3" json:"text,omitempty"`                                               // for system_broadcast
	ActionId        string   `protobuf:"bytes,14,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`                       // correlation id for action_ack/error
	SnapshotVersion uint64   `protobuf:"varint,15,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"` // for equity delta
	Equity          *float64 `protobuf:"fixed64,16,opt,name=equity,proto3,oneof" json:"equity,omitempty"`                                   // for equity delta (player_id identifies owner)
	ReactionId      string   `protobuf:"bytes,17,opt,name=reaction_id,json=reactionId,proto3" json:"reaction_id,omitempty"`                 // ephemeral table reaction catalog key
	TargetPlayerId  string   `protobuf:"bytes,18,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`   // destination for thrown objects
	PurchaseId      string   `protobuf:"bytes,19,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`                 // for sandbox_purchase_update or reaction_purchase_update
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_poker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerMessage) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ServerMessage) GetSnapshot() *TableSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ServerMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ServerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServerMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServerMessage) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *ServerMessage) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *ServerMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ServerMessage) GetSeatsTaken() int32 {
	if x != nil {
		return x.SeatsTaken
	}
	return 0
}

func (x *ServerMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ServerMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ServerMessage) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ServerMessage) GetSnapshotVersion() uint64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *ServerMessage) GetEquity() float64 {
	if x != nil && x.Equity != nil {
		return *x.Equity
	}
	return 0
}

func (x *ServerMessage) GetReactionId() string {
	if x != nil {
		return x.ReactionId
	}
	return ""
}

func (x *ServerMessage) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *ServerMessage) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

var File_poker_proto protoreflect.FileDescriptor

const file_poker_proto_rawDesc = "" +
	"\n" +
	"\vpoker.proto\x12\x05poker\".\n" +
	"\x04Card\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\tR\x04rank\x12\x12\n" +
	"\x04suit\x18\x02 \x01(\tR\x04suit\"\xb2\x06\n" +
	"\x04Seat\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\x03R\x05stack\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12 \n" +
	"\vcontributed\x18\x05 \x01(\x03R\vcontributed\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x06 \x03(\tR\tholeCards\x12\x1b\n" +
	"\x06equity\x18\a \x01(\x01H\x00R\x06equity\x88\x01\x01\x12#\n" +
	"\rhand_category\x18\b \x01(\tR\fhandCategory\x12)\n" +
	"\x10connection_state\x18\t \x01(\tR\x0fconnectionState\x12\x1e\n" +
	"\bdealt_in\x18\n" +
	" \x01(\bH\x01R\adealtIn\x88\x01\x01\x12\x19\n" +
	"\x05ready\x18\v \x01(\bH\x02R\x05ready\x88\x01\x01\x12.\n" +
	"\x13hole_cards_revealed\x18\f \x03(\bR\x11holeCardsRevealed\x122\n" +
	"\x13stack_at_hand_start\x18\r \x01(\x03H\x03R\x10stackAtHandStart\x88\x01\x01\x12 \n" +
	"\ftime_bank_ms\x18\x0e \x01(\x03R\n" +
	"timeBankMs\x12\x1d\n" +
	"\n" +
	"hand_score\x18\x0f \x01(\rR\thandScore\x12\"\n" +
	"\n" +
	"avatar_url\x18\x10 \x01(\tH\x04R\tavatarUrl\x88\x01\x01\x12,\n" +
	"\x0fplaystyle_badge\x18\x11 \x01(\tH\x05R\x0eplaystyleBadge\x88\x01\x01\x12%\n" +
	"\frun_it_twice\x18\x12 \x01(\bH\x06R\n" +
	"runItTwice\x88\x01\x01\x12\"\n" +
	"\n" +
	"auto_rebuy\x18\x13 \x01(\bH\aR\tautoRebuy\x88\x01\x01\x12%\n" +
	"\x0ecurrent_streak\x18\x14 \x01(\x05R\rcurrentStreakB\t\n" +
	"\a_equityB\v\n" +
	"\t_dealt_inB\b\n" +
	"\x06_readyB\x16\n" +
	"\x14_stack_at_hand_startB\r\n" +
	"\v_avatar_urlB\x12\n" +
	"\x10_playstyle_badgeB\x0f\n" +
	"\r_run_it_twiceB\r\n" +
	"\v_auto_rebuy\"n\n" +
	"\x0fBlindEscalation\x12)\n" +
	"\x10interval_minutes\x18\x01 \x01(\x05R\x0fintervalMinutes\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x05R\n" +
	"multiplier\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x03R\x03max\"\x95\x05\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\x12#\n" +
	"\rcurrency_mode\x18\x03 \x01(\tR\fcurrencyMode\x12\x1f\n" +
	"\vsmall_blind\x18\x04 \x01(\x03R\n" +
	"smallBlind\x12\x1b\n" +
	"\tbig_blind\x18\x05 \x01(\x03R\bbigBlind\x12\x1b\n" +
	"\tmax_seats\x18\x06 \x01(\x05R\bmaxSeats\x12\x1c\n" +
	"\n" +
	"buy_in_min\x18\a \x01(\x03R\bbuyInMin\x12\x1c\n" +
	"\n" +
	"buy_in_max\x18\b \x01(\x03R\bbuyInMax\x12&\n" +
	"\x0fentry_fee_cents\x18\t \x01(\x03R\rentryFeeCents\x12\x1d\n" +
	"\n" +
	"share_code\x18\n" +
	" \x01(\tR\tshareCode\x12A\n" +
	"\x10blind_escalation\x18\v \x01(\v2\x16.poker.BlindEscalationR\x0fblindEscalation\x120\n" +
	"\x14turn_timeout_seconds\x18\f \x01(\x05R\x12turnTimeoutSeconds\x124\n" +
	"\x16equity_display_enabled\x18\r \x01(\bR\x14equityDisplayEnabled\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1f\n" +
	"\vseats_taken\x18\x0f \x01(\x05R\n" +
	"seatsTaken\x12\x1d\n" +
	"\n" +
	"created_by\x18\x10 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12/\n" +
	"\x14run_it_twice_enabled\x18\x12 \x01(\bR\x11runItTwiceEnabled\"\xac\x03\n" +
	"\fLegalActions\x12\x18\n" +
	"\aactions\x18\x01 \x03(\tR\aactions\x12\x1f\n" +
	"\vcall_amount\x18\x02 \x01(\x03R\n" +
	"callAmount\x12 \n" +
	"\fmin_raise_to\x18\x03 \x01(\x03R\n" +
	"minRaiseTo\x12 \n" +
	"\fmax_raise_to\x18\x04 \x01(\x03R\n" +
	"maxRaiseTo\x12\x12\n" +
	"\x04step\x18\x05 \x01(\x03R\x04step\x121\n" +
	"\x14current_contribution\x18\x06 \x01(\x03R\x13currentContribution\x12\x1f\n" +
	"\vcurrent_bet\x18\a \x01(\x03R\n" +
	"currentBet\x122\n" +
	"\x16one_third_pot_raise_to\x18\b \x01(\x03R\x12oneThirdPotRaiseTo\x12)\n" +
	"\x11half_pot_raise_to\x18\t \x01(\x03R\x0ehalfPotRaiseTo\x124\n" +
	"\x17two_thirds_pot_raise_to\x18\n" +
	" \x01(\x03R\x13twoThirdsPotRaiseTo\x12 \n" +
	"\fpot_raise_to\x18\v \x01(\x03R\n" +
	"potRaiseTo\"M\n" +
	"\x03Pot\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12.\n" +
	"\x13eligible_player_ids\x18\x02 \x03(\tR\x11eligiblePlayerIds\"\xc9\x02\n" +
	"\tPotResult\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12#\n" +
	"\rpayout_amount\x18\x02 \x01(\x03R\fpayoutAmount\x12.\n" +
	"\x13eligible_player_ids\x18\x03 \x03(\tR\x11eligiblePlayerIds\x12*\n" +
	"\x11winner_player_ids\x18\x04 \x03(\tR\x0fwinnerPlayerIds\x127\n" +
	"\apayouts\x18\x05 \x03(\v2\x1d.poker.PotResult.PayoutsEntryR\apayouts\x12\x16\n" +
	"\x06refund\x18\x06 \x01(\bR\x06refund\x12\x16\n" +
	"\x06runout\x18\a \x01(\x05R\x06runout\x1a:\n" +
	"\fPayoutsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"r\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xc4\x01\n" +
	"\rTableReaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vreaction_id\x18\x03 \x01(\tR\n" +
	"reactionId\x12(\n" +
	"\x10target_player_id\x18\x04 \x01(\tR\x0etargetPlayerId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"\xb0\x0e\n" +
	"\rTableSnapshot\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x14\n" +
	"\x05board\x18\x02 \x03(\tR\x05board\x12!\n" +
	"\x05seats\x18\x03 \x03(\v2\v.poker.SeatR\x05seats\x12;\n" +
	"\apayouts\x18\x04 \x03(\v2!.poker.TableSnapshot.PayoutsEntryR\apayouts\x12\x18\n" +
	"\awinners\x18\x05 \x03(\tR\awinners\x12\x12\n" +
	"\x04rake\x18\x06 \x01(\x03R\x04rake\x12*\n" +
	"\x11current_player_id\x18\a \x01(\tR\x0fcurrentPlayerId\x128\n" +
	"\rlegal_actions\x18\b \x01(\v2\x13.poker.LegalActionsR\flegalActions\x125\n" +
	"\x17action_deadline_unix_ms\x18\t \x01(\x03R\x14actionDeadlineUnixMs\x12)\n" +
	"\x11next_hand_unix_ms\x18\n" +
	" \x01(\x03R\x0enextHandUnixMs\x120\n" +
	"\x14won_without_showdown\x18\v \x01(\bR\x12wonWithoutShowdown\x12.\n" +
	"\x13shuffle_commit_hash\x18\f \x01(\tR\x11shuffleCommitHash\x125\n" +
	"\x17shuffle_server_seed_hex\x18\r \x01(\tR\x14shuffleServerSeedHex\x121\n" +
	"\x15small_blind_player_id\x18\x0e \x01(\tR\x12smallBlindPlayerId\x12-\n" +
	"\x13big_blind_player_id\x18\x0f \x01(\tR\x10bigBlindPlayerId\x12(\n" +
	"\x10dealer_player_id\x18\x10 \x01(\tR\x0edealerPlayerId\x12)\n" +
	"\x10snapshot_version\x18\x11 \x01(\x04R\x0fsnapshotVersion\x12\x1e\n" +
	"\x04pots\x18\x12 \x03(\v2\n" +
	".poker.PotR\x04pots\x12\x17\n" +
	"\ahand_id\x18\x13 \x01(\tR\x06handId\x121\n" +
	"\vpot_results\x18\x14 \x03(\v2\x10.poker.PotResultR\n" +
	"potResults\x12)\n" +
	"\x10protocol_version\x18\x15 \x01(\rR\x0fprotocolVersion\x12/\n" +
	"\x14idle_removal_unix_ms\x18\x16 \x01(\x03R\x11idleRemovalUnixMs\x12>\n" +
	"\x1caction_base_deadline_unix_ms\x18\x17 \x01(\x03R\x18actionBaseDeadlineUnixMs\x127\n" +
	"\rchat_messages\x18\x18 \x03(\v2\x12.poker.ChatMessageR\fchatMessages\x122\n" +
	"\treactions\x18\x19 \x03(\v2\x14.poker.TableReactionR\treactions\x12/\n" +
	"\x13action_preselection\x18\x1a \x01(\tR\x12actionPreselection\x12<\n" +
	"\x1aaction_preselection_amount\x18\x1b \x01(\x03R\x18actionPreselectionAmount\x126\n" +
	"\x17prospective_call_amount\x18\x1c \x01(\x03R\x15prospectiveCallAmount\x12(\n" +
	"\x10root_commit_hash\x18\x1d \x01(\tR\x0erootCommitHash\x12[\n" +
	"\x13revealed_card_salts\x18\x1e \x03(\v2+.poker.TableSnapshot.RevealedCardSaltsEntryR\x11revealedCardSalts\x12d\n" +
	"\x16unrevealed_card_hashes\x18\x1f \x03(\v2..poker.TableSnapshot.UnrevealedCardHashesEntryR\x14unrevealedCardHashes\x12!\n" +
	"\frunout_cards\x18  \x03(\tR\vrunoutCards\x12\x1b\n" +
	"\tboard_two\x18! \x03(\tR\bboardTwo\x12$\n" +
	"\x0eboard_split_at\x18\" \x01(\x05R\fboardSplitAt\x1a:\n" +
	"\fPayoutsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aY\n" +
	"\x16RevealedCardSaltsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.poker.RevealedSaltR\x05value:\x028\x01\x1aG\n" +
	"\x19UnrevealedCardHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\fRevealedSalt\x12\x12\n" +
	"\x04card\x18\x01 \x01(\tR\x04card\x12\x19\n" +
	"\bsalt_hex\x18\x02 \x01(\tR\asaltHex\"\xc1\x04\n" +
	"\rClientMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"share_code\x18\x03 \x01(\tR\tshareCode\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1b\n" +
	"\taction_id\x18\a \x01(\tR\bactionId\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12:\n" +
	"\x19expected_snapshot_version\x18\t \x01(\x04R\x17expectedSnapshotVersion\x12(\n" +
	"\x10expected_hand_id\x18\n" +
	" \x01(\tR\x0eexpectedHandId\x12\"\n" +
	"\n" +
	"card_index\x18\v \x01(\x05H\x00R\tcardIndex\x88\x01\x01\x12\x1f\n" +
	"\vreaction_id\x18\f \x01(\tR\n" +
	"reactionId\x12(\n" +
	"\x10target_player_id\x18\r \x01(\tR\x0etargetPlayerId\x12'\n" +
	"\x0fturnstile_token\x18\x0e \x01(\tR\x0eturnstileToken\x12%\n" +
	"\frun_it_twice\x18\x0f \x01(\bH\x01R\n" +
	"runItTwice\x88\x01\x01\x12%\n" +
	"\x0eexpected_stage\x18\x10 \x01(\tR\rexpectedStageB\r\n" +
	"\v_card_indexB\x0f\n" +
	"\r_run_it_twice\"\xc4\x04\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x120\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x14.poker.TableSnapshotR\bsnapshot\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\tR\bplayerId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x10\n" +
	"\x03key\x18\a \x01(\tR\x03key\x12\x14\n" +
	"\x05stars\x18\b \x01(\x05R\x05stars\x12\x1f\n" +
	"\x04room\x18\t \x01(\v2\v.poker.RoomR\x04room\x12\x17\n" +
	"\aroom_id\x18\n" +
	" \x01(\tR\x06roomId\x12\x1f\n" +
	"\vseats_taken\x18\v \x01(\x05R\n" +
	"seatsTaken\x12\x16\n" +
	"\x06amount\x18\f \x01(\x03R\x06amount\x12\x12\n" +
	"\x04text\x18\r \x01(\tR\x04text\x12\x1b\n" +
	"\taction_id\x18\x0e \x01(\tR\bactionId\x12)\n" +
	"\x10snapshot_version\x18\x0f \x01(\x04R\x0fsnapshotVersion\x12\x1b\n" +
	"\x06equity\x18\x10 \x01(\x01H\x00R\x06equity\x88\x01\x01\x12\x1f\n" +
	"\vreaction_id\x18\x11 \x01(\tR\n" +
	"reactionId\x12(\n" +
	"\x10target_player_id\x18\x12 \x01(\tR\x0etargetPlayerId\x12\x1f\n" +
	"\vpurchase_id\x18\x13 \x01(\tR\n" +
	"purchaseIdB\t\n" +
	"\a_equityB>Z<gopkg.aoctech.app/poker/api/internal/api/v1/proto;pokerprotob\x06proto3"

var (
	file_poker_proto_rawDescOnce sync.Once
	file_poker_proto_rawDescData []byte
)

func file_poker_proto_rawDescGZIP() []byte {
	file_poker_proto_rawDescOnce.Do(func() {
		file_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)))
	})
	return file_poker_proto_rawDescData
}

var file_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_poker_proto_goTypes = []any{
	(*Card)(nil),            // 0: poker.Card
	(*Seat)(nil),            // 1: poker.Seat
	(*BlindEscalation)(nil), // 2: poker.BlindEscalation
	(*Room)(nil),            // 3: poker.Room
	(*LegalActions)(nil),    // 4: poker.LegalActions
	(*Pot)(nil),             // 5: poker.Pot
	(*PotResult)(nil),       // 6: poker.PotResult
	(*ChatMessage)(nil),     // 7: poker.ChatMessage
	(*TableReaction)(nil),   // 8: poker.TableReaction
	(*TableSnapshot)(nil),   // 9: poker.TableSnapshot
	(*RevealedSalt)(nil),    // 10: poker.RevealedSalt
	(*ClientMessage)(nil),   // 11: poker.ClientMessage
	(*ServerMessage)(nil),   // 12: poker.ServerMessage
	nil,                     // 13: poker.PotResult.PayoutsEntry
	nil,                     // 14: poker.TableSnapshot.PayoutsEntry
	nil,                     // 15: poker.TableSnapshot.RevealedCardSaltsEntry
	nil,                     // 16: poker.TableSnapshot.UnrevealedCardHashesEntry
}
var file_poker_proto_depIdxs = []int32{
	2,  // 0: poker.Room.blind_escalation:type_name -> poker.BlindEscalation
	13, // 1: poker.PotResult.payouts:type_name -> poker.PotResult.PayoutsEntry
	1,  // 2: poker.TableSnapshot.seats:type_name -> poker.Seat
	14, // 3: poker.TableSnapshot.payouts:type_name -> poker.TableSnapshot.PayoutsEntry
	4,  // 4: poker.TableSnapshot.legal_actions:type_name -> poker.LegalActions
	5,  // 5: poker.TableSnapshot.pots:type_name -> poker.Pot
	6,  // 6: poker.TableSnapshot.pot_results:type_name -> poker.PotResult
	7,  // 7: poker.TableSnapshot.chat_messages:type_name -> poker.ChatMessage
	8,  // 8: poker.TableSnapshot.reactions:type_name -> poker.TableReaction
	15, // 9: poker.TableSnapshot.revealed_card_salts:type_name -> poker.TableSnapshot.RevealedCardSaltsEntry
	16, // 10: poker.TableSnapshot.unrevealed_card_hashes:type_name -> poker.TableSnapshot.UnrevealedCardHashesEntry
	9,  // 11: poker.ServerMessage.snapshot:type_name -> poker.TableSnapshot
	3,  // 12: poker.ServerMessage.room:type_name -> poker.Room
	10, // 13: poker.TableSnapshot.RevealedCardSaltsEntry.value:type_name -> poker.RevealedSalt
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_poker_proto_init() }
func file_poker_proto_init() {
	if File_poker_proto != nil {
		return
	}
	file_poker_proto_msgTypes[1].OneofWrappers = []any{}
	file_poker_proto_msgTypes[11].OneofWrappers = []any{}
	file_poker_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poker_proto_goTypes,
		DependencyIndexes: file_poker_proto_depIdxs,
		MessageInfos:      file_poker_proto_msgTypes,
	}.Build()
	File_poker_proto = out.File
	file_poker_proto_goTypes = nil
	file_poker_proto_depIdxs = nil
}
