// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.36.1
// source: lobby.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pokerlobby";

/**
 * Field 9 is `poker.Room`. `room_created` only needs to know a room came with
 * the frame (the lobby then re-reads the bucket aggregate over HTTP; #205), so
 * the body is deliberately empty and skipped — while staying a message, so it
 * decodes to `undefined` when absent, exactly as it does in the full codec.
 */
export interface RoomRef {
}

export interface SocialEvent {
  event_id: string;
  type: string;
  room_id: string;
}

export interface LobbyServerMessage {
  type: string;
  code: string;
  room?: RoomRef | undefined;
  room_id: string;
  seats_taken: number;
  amount: number;
  text: string;
  purchase_id: string;
  social_event?: SocialEvent | undefined;
  unread_count: number;
}

/** The gateway only ever sends `auth` (the token frame) and `ping`. */
export interface LobbyClientMessage {
  type: string;
  token: string;
}

function createBaseRoomRef(): RoomRef {
  return {};
}

export const RoomRef: MessageFns<RoomRef> = {
  encode(_: RoomRef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomRef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRoomRef();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): RoomRef {
    return {};
  },

  toJSON(_: RoomRef): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomRef>, I>>(base?: I): RoomRef {
    return RoomRef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomRef>, I>>(_: I): RoomRef {
    const message = createBaseRoomRef();
    return message;
  },
};

function createBaseSocialEvent(): SocialEvent {
  return { event_id: "", type: "", room_id: "" };
}

export const SocialEvent: MessageFns<SocialEvent> = {
  encode(message: SocialEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event_id !== "") {
      writer.uint32(10).string(message.event_id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.room_id !== "") {
      writer.uint32(34).string(message.room_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocialEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSocialEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.event_id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.room_id = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SocialEvent {
    return {
      event_id: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      room_id: isSet(object.roomId)
        ? globalThis.String(object.roomId)
        : isSet(object.room_id)
        ? globalThis.String(object.room_id)
        : "",
    };
  },

  toJSON(message: SocialEvent): unknown {
    const obj: any = {};
    if (message.event_id !== "") {
      obj.eventId = message.event_id;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.room_id !== "") {
      obj.roomId = message.room_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SocialEvent>, I>>(base?: I): SocialEvent {
    return SocialEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocialEvent>, I>>(object: I): SocialEvent {
    const message = createBaseSocialEvent();
    message.event_id = object.event_id ?? "";
    message.type = object.type ?? "";
    message.room_id = object.room_id ?? "";
    return message;
  },
};

function createBaseLobbyServerMessage(): LobbyServerMessage {
  return {
    type: "",
    code: "",
    room: undefined,
    room_id: "",
    seats_taken: 0,
    amount: 0,
    text: "",
    purchase_id: "",
    social_event: undefined,
    unread_count: 0,
  };
}

export const LobbyServerMessage: MessageFns<LobbyServerMessage> = {
  encode(message: LobbyServerMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.code !== "") {
      writer.uint32(50).string(message.code);
    }
    if (message.room !== undefined) {
      RoomRef.encode(message.room, writer.uint32(74).fork()).join();
    }
    if (message.room_id !== "") {
      writer.uint32(82).string(message.room_id);
    }
    if (message.seats_taken !== 0) {
      writer.uint32(88).int32(message.seats_taken);
    }
    if (message.amount !== 0) {
      writer.uint32(96).int64(message.amount);
    }
    if (message.text !== "") {
      writer.uint32(106).string(message.text);
    }
    if (message.purchase_id !== "") {
      writer.uint32(154).string(message.purchase_id);
    }
    if (message.social_event !== undefined) {
      SocialEvent.encode(message.social_event, writer.uint32(162).fork()).join();
    }
    if (message.unread_count !== 0) {
      writer.uint32(168).int32(message.unread_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LobbyServerMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLobbyServerMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.room = RoomRef.decode(reader, reader.uint32());
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.room_id = reader.string();
            continue;
          }
          case 11: {
            if (tag !== 88) {
              break;
            }

            message.seats_taken = reader.int32();
            continue;
          }
          case 12: {
            if (tag !== 96) {
              break;
            }

            message.amount = longToNumber(reader.int64());
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.text = reader.string();
            continue;
          }
          case 19: {
            if (tag !== 154) {
              break;
            }

            message.purchase_id = reader.string();
            continue;
          }
          case 20: {
            if (tag !== 162) {
              break;
            }

            message.social_event = SocialEvent.decode(reader, reader.uint32());
            continue;
          }
          case 21: {
            if (tag !== 168) {
              break;
            }

            message.unread_count = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LobbyServerMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      room: isSet(object.room) ? RoomRef.fromJSON(object.room) : undefined,
      room_id: isSet(object.roomId)
        ? globalThis.String(object.roomId)
        : isSet(object.room_id)
        ? globalThis.String(object.room_id)
        : "",
      seats_taken: isSet(object.seatsTaken)
        ? globalThis.Number(object.seatsTaken)
        : isSet(object.seats_taken)
        ? globalThis.Number(object.seats_taken)
        : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      purchase_id: isSet(object.purchaseId)
        ? globalThis.String(object.purchaseId)
        : isSet(object.purchase_id)
        ? globalThis.String(object.purchase_id)
        : "",
      social_event: isSet(object.socialEvent)
        ? SocialEvent.fromJSON(object.socialEvent)
        : isSet(object.social_event)
        ? SocialEvent.fromJSON(object.social_event)
        : undefined,
      unread_count: isSet(object.unreadCount)
        ? globalThis.Number(object.unreadCount)
        : isSet(object.unread_count)
        ? globalThis.Number(object.unread_count)
        : 0,
    };
  },

  toJSON(message: LobbyServerMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.room !== undefined) {
      obj.room = RoomRef.toJSON(message.room);
    }
    if (message.room_id !== "") {
      obj.roomId = message.room_id;
    }
    if (message.seats_taken !== 0) {
      obj.seatsTaken = Math.round(message.seats_taken);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.purchase_id !== "") {
      obj.purchaseId = message.purchase_id;
    }
    if (message.social_event !== undefined) {
      obj.socialEvent = SocialEvent.toJSON(message.social_event);
    }
    if (message.unread_count !== 0) {
      obj.unreadCount = Math.round(message.unread_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LobbyServerMessage>, I>>(base?: I): LobbyServerMessage {
    return LobbyServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LobbyServerMessage>, I>>(object: I): LobbyServerMessage {
    const message = createBaseLobbyServerMessage();
    message.type = object.type ?? "";
    message.code = object.code ?? "";
    message.room = (object.room !== undefined && object.room !== null) ? RoomRef.fromPartial(object.room) : undefined;
    message.room_id = object.room_id ?? "";
    message.seats_taken = object.seats_taken ?? 0;
    message.amount = object.amount ?? 0;
    message.text = object.text ?? "";
    message.purchase_id = object.purchase_id ?? "";
    message.social_event = (object.social_event !== undefined && object.social_event !== null)
      ? SocialEvent.fromPartial(object.social_event)
      : undefined;
    message.unread_count = object.unread_count ?? 0;
    return message;
  },
};

function createBaseLobbyClientMessage(): LobbyClientMessage {
  return { type: "", token: "" };
}

export const LobbyClientMessage: MessageFns<LobbyClientMessage> = {
  encode(message: LobbyClientMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LobbyClientMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLobbyClientMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.token = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LobbyClientMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: LobbyClientMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LobbyClientMessage>, I>>(base?: I): LobbyClientMessage {
    return LobbyClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LobbyClientMessage>, I>>(object: I): LobbyClientMessage {
    const message = createBaseLobbyClientMessage();
    message.type = object.type ?? "";
    message.token = object.token ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
