// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.19.6
// source: poker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "poker";

export interface Card {
  rank: string;
  suit: string;
}

export interface Seat {
  player_id: string;
  name: string;
  stack: number;
  state: string;
  contributed: number;
  hole_cards: string[];
  equity?: number | undefined;
  hand_category: string;
  /** connected | disconnected */
  connection_state: string;
  /**
   * True when this seat belongs to the hand identified by TableSnapshot.hand_id.
   * A seat can be active while false when it returns mid-hand for the next deal.
   * Optional so a new client can distinguish an old server (field absent)
   * from an explicit false for a player waiting for the next hand.
   */
  dealt_in?:
    | boolean
    | undefined;
  /**
   * The next-hand opt-in. During a live hand a player can be folded from the
   * current round while ready=false already communicates "paused afterwards".
   */
  ready?:
    | boolean
    | undefined;
  /**
   * Public reveal mask for the two hole-card positions. A player's own cards
   * are always visible to themselves; this mask says what everyone may see.
   */
  hole_cards_revealed: boolean[];
  /**
   * Stack before this hand posted blinds or accepted any wager. Optional so
   * clients can fall back safely while API instances are rolling.
   */
  stack_at_hand_start?: number | undefined;
}

export interface BlindEscalation {
  interval_minutes: number;
  multiplier: number;
  max: number;
}

export interface Room {
  room_id: string;
  visibility: string;
  currency_mode: string;
  small_blind: number;
  big_blind: number;
  max_seats: number;
  buy_in_min: number;
  buy_in_max: number;
  entry_fee_cents: number;
  share_code: string;
  blind_escalation: BlindEscalation | undefined;
  turn_timeout_seconds: number;
  equity_display_enabled: boolean;
  status: string;
  seats_taken: number;
  created_by: string;
  created_at: string;
}

export interface LegalActions {
  /** subset of fold|check|call|raise */
  actions: string[];
  /** chips owed to call (0 when a check is available) */
  call_amount: number;
  /** smallest total bet a raise may reach */
  min_raise_to: number;
  /** largest total bet (all-in): viewer stack + already contributed */
  max_raise_to: number;
  /** raise increment for the + / - stepper */
  step: number;
  /** viewer contribution in this betting street */
  current_contribution: number;
  /** highest contribution in this betting street */
  current_bet: number;
  one_third_pot_raise_to: number;
  half_pot_raise_to: number;
  two_thirds_pot_raise_to: number;
  pot_raise_to: number;
}

export interface Pot {
  amount: number;
  eligible_player_ids: string[];
}

export interface PotResult {
  /** gross layer amount before rake */
  amount: number;
  /** net contested payout, or refund amount */
  payout_amount: number;
  eligible_player_ids: string[];
  /** empty for refunds */
  winner_player_ids: string[];
  /** exact per-player credits, including odd chips */
  payouts: { [key: string]: number };
  /** true for uncalled/orphaned contribution returns */
  refund: boolean;
}

export interface PotResult_PayoutsEntry {
  key: string;
  value: number;
}

export interface TableSnapshot {
  stage: string;
  board: string[];
  seats: Seat[];
  payouts: { [key: string]: number };
  winners: string[];
  rake: number;
  current_player_id: string;
  legal_actions: LegalActions | undefined;
  action_deadline_unix_ms: number;
  next_hand_unix_ms: number;
  won_without_showdown: boolean;
  shuffle_commit_hash: string;
  shuffle_server_seed_hex: string;
  small_blind_player_id: string;
  big_blind_player_id: string;
  dealer_player_id: string;
  snapshot_version: number;
  pots: Pot[];
  hand_id: string;
  pot_results: PotResult[];
  /**
   * Allows clients to apply explicit compatibility fallbacks during rolling
   * deployments instead of mistaking absent proto3 fields for false.
   */
  protocol_version: number;
  idle_removal_unix_ms: number;
}

export interface TableSnapshot_PayoutsEntry {
  key: string;
  value: number;
}

/** ClientMessage is sent from the client to the server. */
export interface ClientMessage {
  /** "auth" | "ping" | "sync_state" | "ready" | "act" | "post_big_blind" | "show_cards" | "keep_seat" | "chat" */
  type: string;
  /** payload fields */
  token: string;
  /** for auth frame */
  share_code: string;
  /** for ready command */
  ready: boolean;
  /** for act command */
  action: string;
  /** for act command */
  amount: number;
  /** for act command */
  action_id: string;
  /** for chat command */
  message: string;
  /** optimistic precondition for act */
  expected_snapshot_version: number;
  /** prevents a delayed action crossing hands */
  expected_hand_id: string;
  /** 0 or 1 for show_cards; absent means both (legacy) */
  card_index?: number | undefined;
}

/** ServerMessage is sent from the server to the client. */
export interface ServerMessage {
  /** "connected" | "pong" | "state" | "chat" | "error" | "removed" | "achievement_unlocked" | "room_created" | "room_updated" | "payment_received" | "system_broadcast" */
  type: string;
  /** payload fields */
  conn_id: string;
  /** for state frame */
  snapshot:
    | TableSnapshot
    | undefined;
  /** for chat frame */
  player_id: string;
  /** for chat frame, error message, or removed reason */
  message: string;
  /** for error frame or removed frame */
  code: string;
  /** for achievement unlocked frame */
  key: string;
  /** for achievement unlocked frame */
  stars: number;
  /** lobby payload fields */
  room:
    | Room
    | undefined;
  /** for room_updated */
  room_id: string;
  /** for room_updated */
  seats_taken: number;
  /** for payment_received */
  amount: number;
  /** for system_broadcast */
  text: string;
  /** correlation id for action_ack/error */
  action_id: string;
  /** for equity delta */
  snapshot_version: number;
  /** for equity delta (player_id identifies owner) */
  equity?: number | undefined;
}

function createBaseCard(): Card {
  return { rank: "", suit: "" };
}

export const Card: MessageFns<Card> = {
  encode(message: Card, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rank !== "") {
      writer.uint32(10).string(message.rank);
    }
    if (message.suit !== "") {
      writer.uint32(18).string(message.suit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Card {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rank = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.suit = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Card>, I>>(base?: I): Card {
    return Card.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Card>, I>>(object: I): Card {
    const message = createBaseCard();
    message.rank = object.rank ?? "";
    message.suit = object.suit ?? "";
    return message;
  },
};

function createBaseSeat(): Seat {
  return {
    player_id: "",
    name: "",
    stack: 0,
    state: "",
    contributed: 0,
    hole_cards: [],
    equity: undefined,
    hand_category: "",
    connection_state: "",
    dealt_in: undefined,
    ready: undefined,
    hole_cards_revealed: [],
    stack_at_hand_start: undefined,
  };
}

export const Seat: MessageFns<Seat> = {
  encode(message: Seat, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.player_id !== "") {
      writer.uint32(10).string(message.player_id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.stack !== 0) {
      writer.uint32(24).int64(message.stack);
    }
    if (message.state !== "") {
      writer.uint32(34).string(message.state);
    }
    if (message.contributed !== 0) {
      writer.uint32(40).int64(message.contributed);
    }
    for (const v of message.hole_cards) {
      writer.uint32(50).string(v!);
    }
    if (message.equity !== undefined) {
      writer.uint32(57).double(message.equity);
    }
    if (message.hand_category !== "") {
      writer.uint32(66).string(message.hand_category);
    }
    if (message.connection_state !== "") {
      writer.uint32(74).string(message.connection_state);
    }
    if (message.dealt_in !== undefined) {
      writer.uint32(80).bool(message.dealt_in);
    }
    if (message.ready !== undefined) {
      writer.uint32(88).bool(message.ready);
    }
    writer.uint32(98).fork();
    for (const v of message.hole_cards_revealed) {
      writer.bool(v);
    }
    writer.join();
    if (message.stack_at_hand_start !== undefined) {
      writer.uint32(104).int64(message.stack_at_hand_start);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Seat {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSeat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.player_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.stack = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.contributed = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.hole_cards.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.equity = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.hand_category = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.connection_state = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.dealt_in = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
        case 12: {
          if (tag === 96) {
            message.hole_cards_revealed.push(reader.bool());

            continue;
          }

          if (tag === 98) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.hole_cards_revealed.push(reader.bool());
            }

            continue;
          }

          break;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.stack_at_hand_start = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Seat>, I>>(base?: I): Seat {
    return Seat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Seat>, I>>(object: I): Seat {
    const message = createBaseSeat();
    message.player_id = object.player_id ?? "";
    message.name = object.name ?? "";
    message.stack = object.stack ?? 0;
    message.state = object.state ?? "";
    message.contributed = object.contributed ?? 0;
    message.hole_cards = object.hole_cards?.map((e) => e) || [];
    message.equity = object.equity ?? undefined;
    message.hand_category = object.hand_category ?? "";
    message.connection_state = object.connection_state ?? "";
    message.dealt_in = object.dealt_in ?? undefined;
    message.ready = object.ready ?? undefined;
    message.hole_cards_revealed = object.hole_cards_revealed?.map((e) => e) || [];
    message.stack_at_hand_start = object.stack_at_hand_start ?? undefined;
    return message;
  },
};

function createBaseBlindEscalation(): BlindEscalation {
  return { interval_minutes: 0, multiplier: 0, max: 0 };
}

export const BlindEscalation: MessageFns<BlindEscalation> = {
  encode(message: BlindEscalation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.interval_minutes !== 0) {
      writer.uint32(8).int32(message.interval_minutes);
    }
    if (message.multiplier !== 0) {
      writer.uint32(16).int32(message.multiplier);
    }
    if (message.max !== 0) {
      writer.uint32(24).int64(message.max);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BlindEscalation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlindEscalation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.interval_minutes = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.multiplier = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.max = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<BlindEscalation>, I>>(base?: I): BlindEscalation {
    return BlindEscalation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BlindEscalation>, I>>(object: I): BlindEscalation {
    const message = createBaseBlindEscalation();
    message.interval_minutes = object.interval_minutes ?? 0;
    message.multiplier = object.multiplier ?? 0;
    message.max = object.max ?? 0;
    return message;
  },
};

function createBaseRoom(): Room {
  return {
    room_id: "",
    visibility: "",
    currency_mode: "",
    small_blind: 0,
    big_blind: 0,
    max_seats: 0,
    buy_in_min: 0,
    buy_in_max: 0,
    entry_fee_cents: 0,
    share_code: "",
    blind_escalation: undefined,
    turn_timeout_seconds: 0,
    equity_display_enabled: false,
    status: "",
    seats_taken: 0,
    created_by: "",
    created_at: "",
  };
}

export const Room: MessageFns<Room> = {
  encode(message: Room, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.room_id !== "") {
      writer.uint32(10).string(message.room_id);
    }
    if (message.visibility !== "") {
      writer.uint32(18).string(message.visibility);
    }
    if (message.currency_mode !== "") {
      writer.uint32(26).string(message.currency_mode);
    }
    if (message.small_blind !== 0) {
      writer.uint32(32).int64(message.small_blind);
    }
    if (message.big_blind !== 0) {
      writer.uint32(40).int64(message.big_blind);
    }
    if (message.max_seats !== 0) {
      writer.uint32(48).int32(message.max_seats);
    }
    if (message.buy_in_min !== 0) {
      writer.uint32(56).int64(message.buy_in_min);
    }
    if (message.buy_in_max !== 0) {
      writer.uint32(64).int64(message.buy_in_max);
    }
    if (message.entry_fee_cents !== 0) {
      writer.uint32(72).int64(message.entry_fee_cents);
    }
    if (message.share_code !== "") {
      writer.uint32(82).string(message.share_code);
    }
    if (message.blind_escalation !== undefined) {
      BlindEscalation.encode(message.blind_escalation, writer.uint32(90).fork()).join();
    }
    if (message.turn_timeout_seconds !== 0) {
      writer.uint32(96).int32(message.turn_timeout_seconds);
    }
    if (message.equity_display_enabled !== false) {
      writer.uint32(104).bool(message.equity_display_enabled);
    }
    if (message.status !== "") {
      writer.uint32(114).string(message.status);
    }
    if (message.seats_taken !== 0) {
      writer.uint32(120).int32(message.seats_taken);
    }
    if (message.created_by !== "") {
      writer.uint32(130).string(message.created_by);
    }
    if (message.created_at !== "") {
      writer.uint32(138).string(message.created_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Room {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.room_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.visibility = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency_mode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.small_blind = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.big_blind = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.max_seats = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.buy_in_min = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.buy_in_max = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.entry_fee_cents = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.share_code = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.blind_escalation = BlindEscalation.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.turn_timeout_seconds = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.equity_display_enabled = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.seats_taken = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.created_by = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Room>, I>>(base?: I): Room {
    return Room.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Room>, I>>(object: I): Room {
    const message = createBaseRoom();
    message.room_id = object.room_id ?? "";
    message.visibility = object.visibility ?? "";
    message.currency_mode = object.currency_mode ?? "";
    message.small_blind = object.small_blind ?? 0;
    message.big_blind = object.big_blind ?? 0;
    message.max_seats = object.max_seats ?? 0;
    message.buy_in_min = object.buy_in_min ?? 0;
    message.buy_in_max = object.buy_in_max ?? 0;
    message.entry_fee_cents = object.entry_fee_cents ?? 0;
    message.share_code = object.share_code ?? "";
    message.blind_escalation = (object.blind_escalation !== undefined && object.blind_escalation !== null)
      ? BlindEscalation.fromPartial(object.blind_escalation)
      : undefined;
    message.turn_timeout_seconds = object.turn_timeout_seconds ?? 0;
    message.equity_display_enabled = object.equity_display_enabled ?? false;
    message.status = object.status ?? "";
    message.seats_taken = object.seats_taken ?? 0;
    message.created_by = object.created_by ?? "";
    message.created_at = object.created_at ?? "";
    return message;
  },
};

function createBaseLegalActions(): LegalActions {
  return {
    actions: [],
    call_amount: 0,
    min_raise_to: 0,
    max_raise_to: 0,
    step: 0,
    current_contribution: 0,
    current_bet: 0,
    one_third_pot_raise_to: 0,
    half_pot_raise_to: 0,
    two_thirds_pot_raise_to: 0,
    pot_raise_to: 0,
  };
}

export const LegalActions: MessageFns<LegalActions> = {
  encode(message: LegalActions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.actions) {
      writer.uint32(10).string(v!);
    }
    if (message.call_amount !== 0) {
      writer.uint32(16).int64(message.call_amount);
    }
    if (message.min_raise_to !== 0) {
      writer.uint32(24).int64(message.min_raise_to);
    }
    if (message.max_raise_to !== 0) {
      writer.uint32(32).int64(message.max_raise_to);
    }
    if (message.step !== 0) {
      writer.uint32(40).int64(message.step);
    }
    if (message.current_contribution !== 0) {
      writer.uint32(48).int64(message.current_contribution);
    }
    if (message.current_bet !== 0) {
      writer.uint32(56).int64(message.current_bet);
    }
    if (message.one_third_pot_raise_to !== 0) {
      writer.uint32(64).int64(message.one_third_pot_raise_to);
    }
    if (message.half_pot_raise_to !== 0) {
      writer.uint32(72).int64(message.half_pot_raise_to);
    }
    if (message.two_thirds_pot_raise_to !== 0) {
      writer.uint32(80).int64(message.two_thirds_pot_raise_to);
    }
    if (message.pot_raise_to !== 0) {
      writer.uint32(88).int64(message.pot_raise_to);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LegalActions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLegalActions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actions.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.call_amount = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.min_raise_to = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.max_raise_to = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.step = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.current_contribution = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.current_bet = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.one_third_pot_raise_to = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.half_pot_raise_to = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.two_thirds_pot_raise_to = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.pot_raise_to = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LegalActions>, I>>(base?: I): LegalActions {
    return LegalActions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LegalActions>, I>>(object: I): LegalActions {
    const message = createBaseLegalActions();
    message.actions = object.actions?.map((e) => e) || [];
    message.call_amount = object.call_amount ?? 0;
    message.min_raise_to = object.min_raise_to ?? 0;
    message.max_raise_to = object.max_raise_to ?? 0;
    message.step = object.step ?? 0;
    message.current_contribution = object.current_contribution ?? 0;
    message.current_bet = object.current_bet ?? 0;
    message.one_third_pot_raise_to = object.one_third_pot_raise_to ?? 0;
    message.half_pot_raise_to = object.half_pot_raise_to ?? 0;
    message.two_thirds_pot_raise_to = object.two_thirds_pot_raise_to ?? 0;
    message.pot_raise_to = object.pot_raise_to ?? 0;
    return message;
  },
};

function createBasePot(): Pot {
  return { amount: 0, eligible_player_ids: [] };
}

export const Pot: MessageFns<Pot> = {
  encode(message: Pot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== 0) {
      writer.uint32(8).int64(message.amount);
    }
    for (const v of message.eligible_player_ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eligible_player_ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Pot>, I>>(base?: I): Pot {
    return Pot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pot>, I>>(object: I): Pot {
    const message = createBasePot();
    message.amount = object.amount ?? 0;
    message.eligible_player_ids = object.eligible_player_ids?.map((e) => e) || [];
    return message;
  },
};

function createBasePotResult(): PotResult {
  return { amount: 0, payout_amount: 0, eligible_player_ids: [], winner_player_ids: [], payouts: {}, refund: false };
}

export const PotResult: MessageFns<PotResult> = {
  encode(message: PotResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== 0) {
      writer.uint32(8).int64(message.amount);
    }
    if (message.payout_amount !== 0) {
      writer.uint32(16).int64(message.payout_amount);
    }
    for (const v of message.eligible_player_ids) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.winner_player_ids) {
      writer.uint32(34).string(v!);
    }
    globalThis.Object.entries(message.payouts).forEach(([key, value]: [string, number]) => {
      PotResult_PayoutsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    if (message.refund !== false) {
      writer.uint32(48).bool(message.refund);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PotResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePotResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.payout_amount = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.eligible_player_ids.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.winner_player_ids.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = PotResult_PayoutsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.payouts[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.refund = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PotResult>, I>>(base?: I): PotResult {
    return PotResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PotResult>, I>>(object: I): PotResult {
    const message = createBasePotResult();
    message.amount = object.amount ?? 0;
    message.payout_amount = object.payout_amount ?? 0;
    message.eligible_player_ids = object.eligible_player_ids?.map((e) => e) || [];
    message.winner_player_ids = object.winner_player_ids?.map((e) => e) || [];
    message.payouts = (globalThis.Object.entries(object.payouts ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.refund = object.refund ?? false;
    return message;
  },
};

function createBasePotResult_PayoutsEntry(): PotResult_PayoutsEntry {
  return { key: "", value: 0 };
}

export const PotResult_PayoutsEntry: MessageFns<PotResult_PayoutsEntry> = {
  encode(message: PotResult_PayoutsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PotResult_PayoutsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePotResult_PayoutsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PotResult_PayoutsEntry>, I>>(base?: I): PotResult_PayoutsEntry {
    return PotResult_PayoutsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PotResult_PayoutsEntry>, I>>(object: I): PotResult_PayoutsEntry {
    const message = createBasePotResult_PayoutsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseTableSnapshot(): TableSnapshot {
  return {
    stage: "",
    board: [],
    seats: [],
    payouts: {},
    winners: [],
    rake: 0,
    current_player_id: "",
    legal_actions: undefined,
    action_deadline_unix_ms: 0,
    next_hand_unix_ms: 0,
    won_without_showdown: false,
    shuffle_commit_hash: "",
    shuffle_server_seed_hex: "",
    small_blind_player_id: "",
    big_blind_player_id: "",
    dealer_player_id: "",
    snapshot_version: 0,
    pots: [],
    hand_id: "",
    pot_results: [],
    protocol_version: 0,
    idle_removal_unix_ms: 0,
  };
}

export const TableSnapshot: MessageFns<TableSnapshot> = {
  encode(message: TableSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stage !== "") {
      writer.uint32(10).string(message.stage);
    }
    for (const v of message.board) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.seats) {
      Seat.encode(v!, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.payouts).forEach(([key, value]: [string, number]) => {
      TableSnapshot_PayoutsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    for (const v of message.winners) {
      writer.uint32(42).string(v!);
    }
    if (message.rake !== 0) {
      writer.uint32(48).int64(message.rake);
    }
    if (message.current_player_id !== "") {
      writer.uint32(58).string(message.current_player_id);
    }
    if (message.legal_actions !== undefined) {
      LegalActions.encode(message.legal_actions, writer.uint32(66).fork()).join();
    }
    if (message.action_deadline_unix_ms !== 0) {
      writer.uint32(72).int64(message.action_deadline_unix_ms);
    }
    if (message.next_hand_unix_ms !== 0) {
      writer.uint32(80).int64(message.next_hand_unix_ms);
    }
    if (message.won_without_showdown !== false) {
      writer.uint32(88).bool(message.won_without_showdown);
    }
    if (message.shuffle_commit_hash !== "") {
      writer.uint32(98).string(message.shuffle_commit_hash);
    }
    if (message.shuffle_server_seed_hex !== "") {
      writer.uint32(106).string(message.shuffle_server_seed_hex);
    }
    if (message.small_blind_player_id !== "") {
      writer.uint32(114).string(message.small_blind_player_id);
    }
    if (message.big_blind_player_id !== "") {
      writer.uint32(122).string(message.big_blind_player_id);
    }
    if (message.dealer_player_id !== "") {
      writer.uint32(130).string(message.dealer_player_id);
    }
    if (message.snapshot_version !== 0) {
      writer.uint32(136).uint64(message.snapshot_version);
    }
    for (const v of message.pots) {
      Pot.encode(v!, writer.uint32(146).fork()).join();
    }
    if (message.hand_id !== "") {
      writer.uint32(154).string(message.hand_id);
    }
    for (const v of message.pot_results) {
      PotResult.encode(v!, writer.uint32(162).fork()).join();
    }
    if (message.protocol_version !== 0) {
      writer.uint32(168).uint32(message.protocol_version);
    }
    if (message.idle_removal_unix_ms !== 0) {
      writer.uint32(176).int64(message.idle_removal_unix_ms);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TableSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTableSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stage = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.board.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.seats.push(Seat.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = TableSnapshot_PayoutsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.payouts[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.winners.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.rake = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.current_player_id = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.legal_actions = LegalActions.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.action_deadline_unix_ms = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.next_hand_unix_ms = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.won_without_showdown = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.shuffle_commit_hash = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.shuffle_server_seed_hex = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.small_blind_player_id = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.big_blind_player_id = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.dealer_player_id = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.snapshot_version = longToNumber(reader.uint64());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.pots.push(Pot.decode(reader, reader.uint32()));
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.hand_id = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.pot_results.push(PotResult.decode(reader, reader.uint32()));
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.protocol_version = reader.uint32();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.idle_removal_unix_ms = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TableSnapshot>, I>>(base?: I): TableSnapshot {
    return TableSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TableSnapshot>, I>>(object: I): TableSnapshot {
    const message = createBaseTableSnapshot();
    message.stage = object.stage ?? "";
    message.board = object.board?.map((e) => e) || [];
    message.seats = object.seats?.map((e) => Seat.fromPartial(e)) || [];
    message.payouts = (globalThis.Object.entries(object.payouts ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.winners = object.winners?.map((e) => e) || [];
    message.rake = object.rake ?? 0;
    message.current_player_id = object.current_player_id ?? "";
    message.legal_actions = (object.legal_actions !== undefined && object.legal_actions !== null)
      ? LegalActions.fromPartial(object.legal_actions)
      : undefined;
    message.action_deadline_unix_ms = object.action_deadline_unix_ms ?? 0;
    message.next_hand_unix_ms = object.next_hand_unix_ms ?? 0;
    message.won_without_showdown = object.won_without_showdown ?? false;
    message.shuffle_commit_hash = object.shuffle_commit_hash ?? "";
    message.shuffle_server_seed_hex = object.shuffle_server_seed_hex ?? "";
    message.small_blind_player_id = object.small_blind_player_id ?? "";
    message.big_blind_player_id = object.big_blind_player_id ?? "";
    message.dealer_player_id = object.dealer_player_id ?? "";
    message.snapshot_version = object.snapshot_version ?? 0;
    message.pots = object.pots?.map((e) => Pot.fromPartial(e)) || [];
    message.hand_id = object.hand_id ?? "";
    message.pot_results = object.pot_results?.map((e) => PotResult.fromPartial(e)) || [];
    message.protocol_version = object.protocol_version ?? 0;
    message.idle_removal_unix_ms = object.idle_removal_unix_ms ?? 0;
    return message;
  },
};

function createBaseTableSnapshot_PayoutsEntry(): TableSnapshot_PayoutsEntry {
  return { key: "", value: 0 };
}

export const TableSnapshot_PayoutsEntry: MessageFns<TableSnapshot_PayoutsEntry> = {
  encode(message: TableSnapshot_PayoutsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TableSnapshot_PayoutsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTableSnapshot_PayoutsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TableSnapshot_PayoutsEntry>, I>>(base?: I): TableSnapshot_PayoutsEntry {
    return TableSnapshot_PayoutsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TableSnapshot_PayoutsEntry>, I>>(object: I): TableSnapshot_PayoutsEntry {
    const message = createBaseTableSnapshot_PayoutsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseClientMessage(): ClientMessage {
  return {
    type: "",
    token: "",
    share_code: "",
    ready: false,
    action: "",
    amount: 0,
    action_id: "",
    message: "",
    expected_snapshot_version: 0,
    expected_hand_id: "",
    card_index: undefined,
  };
}

export const ClientMessage: MessageFns<ClientMessage> = {
  encode(message: ClientMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.share_code !== "") {
      writer.uint32(26).string(message.share_code);
    }
    if (message.ready !== false) {
      writer.uint32(32).bool(message.ready);
    }
    if (message.action !== "") {
      writer.uint32(42).string(message.action);
    }
    if (message.amount !== 0) {
      writer.uint32(48).int64(message.amount);
    }
    if (message.action_id !== "") {
      writer.uint32(58).string(message.action_id);
    }
    if (message.message !== "") {
      writer.uint32(66).string(message.message);
    }
    if (message.expected_snapshot_version !== 0) {
      writer.uint32(72).uint64(message.expected_snapshot_version);
    }
    if (message.expected_hand_id !== "") {
      writer.uint32(82).string(message.expected_hand_id);
    }
    if (message.card_index !== undefined) {
      writer.uint32(88).int32(message.card_index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.share_code = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.action_id = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.expected_snapshot_version = longToNumber(reader.uint64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.expected_hand_id = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.card_index = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ClientMessage>, I>>(base?: I): ClientMessage {
    return ClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientMessage>, I>>(object: I): ClientMessage {
    const message = createBaseClientMessage();
    message.type = object.type ?? "";
    message.token = object.token ?? "";
    message.share_code = object.share_code ?? "";
    message.ready = object.ready ?? false;
    message.action = object.action ?? "";
    message.amount = object.amount ?? 0;
    message.action_id = object.action_id ?? "";
    message.message = object.message ?? "";
    message.expected_snapshot_version = object.expected_snapshot_version ?? 0;
    message.expected_hand_id = object.expected_hand_id ?? "";
    message.card_index = object.card_index ?? undefined;
    return message;
  },
};

function createBaseServerMessage(): ServerMessage {
  return {
    type: "",
    conn_id: "",
    snapshot: undefined,
    player_id: "",
    message: "",
    code: "",
    key: "",
    stars: 0,
    room: undefined,
    room_id: "",
    seats_taken: 0,
    amount: 0,
    text: "",
    action_id: "",
    snapshot_version: 0,
    equity: undefined,
  };
}

export const ServerMessage: MessageFns<ServerMessage> = {
  encode(message: ServerMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.conn_id !== "") {
      writer.uint32(18).string(message.conn_id);
    }
    if (message.snapshot !== undefined) {
      TableSnapshot.encode(message.snapshot, writer.uint32(26).fork()).join();
    }
    if (message.player_id !== "") {
      writer.uint32(34).string(message.player_id);
    }
    if (message.message !== "") {
      writer.uint32(42).string(message.message);
    }
    if (message.code !== "") {
      writer.uint32(50).string(message.code);
    }
    if (message.key !== "") {
      writer.uint32(58).string(message.key);
    }
    if (message.stars !== 0) {
      writer.uint32(64).int32(message.stars);
    }
    if (message.room !== undefined) {
      Room.encode(message.room, writer.uint32(74).fork()).join();
    }
    if (message.room_id !== "") {
      writer.uint32(82).string(message.room_id);
    }
    if (message.seats_taken !== 0) {
      writer.uint32(88).int32(message.seats_taken);
    }
    if (message.amount !== 0) {
      writer.uint32(96).int64(message.amount);
    }
    if (message.text !== "") {
      writer.uint32(106).string(message.text);
    }
    if (message.action_id !== "") {
      writer.uint32(114).string(message.action_id);
    }
    if (message.snapshot_version !== 0) {
      writer.uint32(120).uint64(message.snapshot_version);
    }
    if (message.equity !== undefined) {
      writer.uint32(129).double(message.equity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.conn_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.snapshot = TableSnapshot.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.player_id = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.stars = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.room = Room.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.room_id = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.seats_taken = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.action_id = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.snapshot_version = longToNumber(reader.uint64());
          continue;
        }
        case 16: {
          if (tag !== 129) {
            break;
          }

          message.equity = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ServerMessage>, I>>(base?: I): ServerMessage {
    return ServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerMessage>, I>>(object: I): ServerMessage {
    const message = createBaseServerMessage();
    message.type = object.type ?? "";
    message.conn_id = object.conn_id ?? "";
    message.snapshot = (object.snapshot !== undefined && object.snapshot !== null)
      ? TableSnapshot.fromPartial(object.snapshot)
      : undefined;
    message.player_id = object.player_id ?? "";
    message.message = object.message ?? "";
    message.code = object.code ?? "";
    message.key = object.key ?? "";
    message.stars = object.stars ?? 0;
    message.room = (object.room !== undefined && object.room !== null) ? Room.fromPartial(object.room) : undefined;
    message.room_id = object.room_id ?? "";
    message.seats_taken = object.seats_taken ?? 0;
    message.amount = object.amount ?? 0;
    message.text = object.text ?? "";
    message.action_id = object.action_id ?? "";
    message.snapshot_version = object.snapshot_version ?? 0;
    message.equity = object.equity ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
