// Card examples from ui/src/lib/achievements.ts.
const achievementExamples = <String, List<String>>{
  'wins': ['AH', 'AD'],
  'hands_played': ['KC', '7D'],
  'comeback': ['5H', '5C'],
  'bluff': ['7C', '2D'],
  'survivor': ['JD', '8S'],
  'looser': ['KH', 'KD'],
  'almost_winner': ['QH', 'QD'],
  'tied': ['TH', 'TS'],
  'bad_beat': ['8H', '8D', '8C'],
  'cooler': ['KH', 'KD', 'KC', '5S', '5D'],
  'cracked_aces': ['AH', 'AS'],
  'fallen_king': ['KD', 'KC'],
  'giant_slayer': ['2H', '7D'],
  'showdown_warrior': ['JH', 'TD'],
  'all_in': ['AS', 'KS'],
  'sandbox_chips_earned': ['TC', 'TD', 'TH', 'TS'],
  'real_money_earned': ['AC', 'AD', 'AH', 'AS'],
  'won_with_pocket_pair': ['9H', '9S'],
  'won_full_table': ['AC', 'KC'],
  'won_heads_up': ['AD', 'TD'],
  'won_with_nuts': ['JH', 'TH'],
  'won_runner_runner': ['4C', '5C'],
  'three_bet_won_no_showdown': ['AH', 'QS'],
  'beat_pocket_aces': ['7S', '8S'],
  'beat_trips_or_better': ['6H', '7H', '8H', '9H', 'TH'],
  'first_hand_allin_win': ['AC', 'AS'],
  'same_pocket_pair_streak': ['8C', '8D'],
  'folded_streak': ['3S', '8D'],
  'four_to_royal_missed': ['TS', 'JS', 'QS', 'KS'],
  'four_to_straight_flush_missed': ['5C', '6C', '7C', '8C'],
  'paid_river_draw_missed': ['AH', '4H'],
  'lost_river_after_leading_turn': ['KS', 'QS'],
  'lost_straight_flush_to_royal': ['9H', 'TH', 'JH', 'QH', 'KH'],
  'all_in_blind': ['back', 'back'],
  'blind_magic': ['back', 'back'],
  'no_rush': ['QS', 'JS'],
  'win_category_royal_flush': ['TH', 'JH', 'QH', 'KH', 'AH'],
};
