// Product labels aligned with ui/src/lib/utils.ts.
const achievementLabels = <String, String>{
  "wins": "Vitórias",
  "hands_played": "Mãos Jogadas",
  "comeback": "De Volta ao Jogo",
  "bluff": "Mestre do Blefe",
  "survivor": "Sobrevivente",
  "looser": "Não Foi Dessa Vez",
  "almost_winner": "Por Um Detalhe",
  "tied": "Dividindo o Pote",
  "bad_beat": "Que Azar!",
  "cooler": "Sem Escapatória",
  "cracked_aces": "Maldito Ás",
  "fallen_king": "KKKKKKKKK",
  "giant_slayer": "Virou o Jogo",
  "showdown_warrior": "Paga pra Ver",
  "all_in": "Tudo ou Nada",
  "sandbox_chips_earned": "Montanha de Fichas",
  "real_money_earned": "Banca de Verdade",
  "won_with_pocket_pair": "Par na Mão",
  "won_full_table": "Dono da Mesa",
  "won_heads_up": "Duelo Vencido",
  "won_with_nuts": "Mão Imbatível",
  "won_runner_runner": "Turn e River Perfeitos",
  "three_bet_won_no_showdown": "Pressão no 3-bet",
  "beat_pocket_aces": "Quebrou os Ases",
  "beat_trips_or_better": "Passou por Cima",
  "first_hand_allin_win": "Chegou Chegando",
  "same_pocket_pair_streak": "Par de Estimação",
  "folded_streak": "Paciência de Pedra",
  "all_in_blind": "All-in às Cegas",
  "blind_magic": "Magia das Cartas",
  "no_rush": "Sem pressa",
  "four_to_royal_missed": "Quase Royal",
  "four_to_straight_flush_missed": "Quase Straight Flush",
  "paid_river_draw_missed": "Pagou e Não Veio",
  "lost_river_after_leading_turn": "Perdeu no River",
  "lost_straight_flush_to_royal": "Azar Histórico",
  "win_category_high_card": "Carta Alta",
  "win_category_pair": "Um Par",
  "win_category_two_pair": "Dois Pares",
  "win_category_three_of_a_kind": "Trinca",
  "win_category_straight": "Sequência",
  "win_category_flush": "Flush",
  "win_category_full_house": "Full House",
  "win_category_four_of_a_kind": "Quadra",
  "win_category_straight_flush": "Straight Flush",
  "win_category_royal_flush": "Royal Flush",
};
String achievementLabel(dynamic key) => achievementLabels[key] ?? "Conquista";
